config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('house/', include("housing.urls", namespace="housing")),
    path('admin/', include("user_admin.urls", namespace="user_admin")),
    path('backoffice/', admin.site.urls),
]

housing/urls.py
from django.urls import path

from . import views

app_name = "housing"

urlpatterns = [
    path("list", views.HousesList.as_view(), name="house-list"),
    path("<int:pk>/detail", views.HouseDetail.as_view(), name="house-detail")
]

user_admin/urls.py
from django.urls import path

from . import views

app_name = "user_admin"

urlpatterns = [
    path("house/list", views.HouseList.as_view(), name="house-list"),
    path("house/create", views.CreateHouse.as_view(), name="house-create"),
    path("house/update/<int:pk>", views.UpdateHouse.as_view(), name="house-update"),
    path("house/<int:pk>/apartment/create", views.CreateApartment.as_view(), name="apartment-create"),
    path("house/apartment/<int:pk>/update", views.UpdateApartment.as_view(), name="apartment-update"),
    path("house/apartment/<int:pk>/resident/create", views.CreateResident.as_view(), name="resident-create")
]

housing/models.py
from django.db import models

# Create your models here.


class House(models.Model):
    CONCRETE = "Concrete"
    WOOD = "Wood"
    Brick = "Brick"
    MATERIAL_CHOICES = (
        (CONCRETE, "Concrete"),
        (WOOD, "Wood"),
        (Brick, "Brick"),
    )

    address = models.TextField(max_length=500, unique=True)
    material = models.CharField(max_length=15, choices=MATERIAL_CHOICES)
    company = models.CharField(max_length=30)


class Apartment(models.Model):
    house = models.ForeignKey(House, on_delete=models.DO_NOTHING)
    number = models.PositiveSmallIntegerField(default=1)
    price = models.IntegerField()
    square = models.IntegerField()
    rooms_count = models.IntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["house", "number"], name="unique apartment number to house")
        ]


class Resident(models.Model):
    MAN = "M"
    WOMEN = "W"

    SEX_CHOICES = (
        (MAN, "M"),
        (WOMEN, "W"),
    )

    apartment = models.ForeignKey(Apartment, on_delete=models.DO_NOTHING)
    first_name = models.CharField(max_length=30)
    second_name = models.CharField(max_length=30)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    age = models.PositiveSmallIntegerField()
    salary = models.PositiveSmallIntegerField(default=None, null=True, blank=True)

user_admin/models.py
from django.db import models

# Create your models here.

user_admin/forms.py
from django import forms
from housing.models import Apartment, Resident


class ApartmentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        exclude = ["house"]


class ResidentForm(forms.ModelForm):
    class Meta:
        model = Resident
        exclude = ["apartment"]

housing/views.py
from django.views.generic import ListView, DetailView

from .models import House, Apartment, Resident

# Create your views here.


class HousesList(ListView):
    model = House
    context_object_name = "houses"


class HouseDetail(DetailView):
    model = House
    context_object_name = "house"

    def get_context_data(self, **kwargs):
        context = super(HouseDetail, self).get_context_data(**kwargs)
        context["apartments"] = Apartment.objects.filter(house_id=self.kwargs["pk"])
        return context

user_admin/views.py
from django.views.generic import CreateView, UpdateView, ListView
from django.shortcuts import reverse
from django.contrib.auth.mixins import UserPassesTestMixin
from housing.models import House, Apartment, Resident
from .forms import ApartmentForm, ResidentForm
# Create your views here.


class AdminGroutPermissionMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name="admin").exists()


class HouseList(AdminGroutPermissionMixin, ListView):
    model = House
    context_object_name = "houses"
    template_name = "user_admin/house_list.html"


class CreateHouse(AdminGroutPermissionMixin, CreateView):
    model = House
    fields = "__all__"
    template_name = "user_admin/house_form.html"
    context_object_name = "house"


class UpdateHouse(AdminGroutPermissionMixin, UpdateView):
    model = House
    fields = "__all__"
    template_name = "user_admin/house_form.html"

    def get_success_url(self):
        return reverse("user_admin:house-update", kwargs={"pk": self.kwargs["pk"]})


class CreateApartment(AdminGroutPermissionMixin, CreateView):
    model = Apartment
    template_name = "user_admin/apartment_form.html"
    form_class = ApartmentForm

    def form_valid(self, form):
        form.instance.house = House.objects.get(pk=self.kwargs["pk"])
        return super(CreateApartment, self).form_valid(form)

    def get_success_url(self):
        return reverse("user_admin:house-update", kwargs={"pk": self.kwargs["pk"]})


class UpdateApartment(AdminGroutPermissionMixin, UpdateView):
    model = Apartment
    template_name = "user_admin/apartment_form.html"
    form_class = ApartmentForm

    def form_valid(self, form):
        form.instance.house = House.objects.get(pk=self.kwargs["pk"])
        return super(UpdateApartment, self).form_valid(form)

    def get_success_url(self):
        return reverse("user_admin:apartment-update", kwargs={"pk": self.kwargs["pk"]})


class CreateResident(AdminGroutPermissionMixin, CreateView):
    model = Resident
    template_name = "user_admin/resident_form.html"
    form_class = ResidentForm

    def form_valid(self, form):
        form.instance.apartment = Apartment.objects.get(pk=self.kwargs["pk"])
        return super(CreateResident, self).form_valid(form)

    def get_success_url(self):
        return reverse("user_admin:apartment-update", kwargs={"pk": self.kwargs["pk"]})

templates/housing/house_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>House detail: {{ house.address }}</title>
</head>
<body>
    <p>{{ house.address }}</p>
    <p>{{ house.material }}</p>
    <p>{{ house.company }}</p>
    {% for apartment in apartments %}
        <p>Appartment number: {{ apartment.number }}</p>
        <p>Price: {{ apartment.price }}</p>
        <p>Square: {{ apartment.square }}</p>
        <p>Rooms: {{ apartment.rooms_count }}</p>
        {% for resident in apartment.resident_set.all %}
            <p>Residents:</p>
            <p>Name: {{ resident.first_name }} {{ resident.second_name }}</p>
            <p>Age: {{ resident.age }}</p>
            <p>Sex: {{ resident.sex }}</p>
            <p>Salary: {{ resident.salary }}</p>
        {% endfor %}
        <br>
    {% endfor %}

</body>
</html>

templates/housing/house_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Houses</title>
</head>
<body>
    {% for house in houses %}
        <p><a href="{% url "housing:house-detail" pk=house.pk %}">{{ house.address }}</a></p>
        <p>{{ house.company }}</p>
        <p>{{ house.material }}</p>
    {% endfor %}

</body>
</html>

templates/user_admin/apartment_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create apartment</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>

</body>
</html>

templates/user_admin/house_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>House Form</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
<a href="{% url "user_admin:apartment-create" pk=house.pk %}">Create apartment</a>
{% for apartment in house.apartment_set.all %}
    <p><a href="{% url "user_admin:apartment-update" pk=apartment.pk %}">Appartment number: {{ apartment.number }}</a></p>
        <p>Price: {{ apartment.price }}</p>
        <p>Square: {{ apartment.square }}</p>
        <p>Rooms: {{ apartment.rooms_count }}</p>
        <a href="{% url "user_admin:resident-create" pk=apartment.pk %}">Create resident</a>
        {% for resident in apartment.resident_set.all %}
            <p>Residents:</p>
            <p>Name: {{ resident.first_name }} {{ resident.second_name }}</p>
            <p>Age: {{ resident.age }}</p>
            <p>Sex: {{ resident.sex }}</p>
            <p>Salary: {{ resident.salary }}</p>
        {% endfor %}
        <br>
{% endfor %}

</body>
</html>

templates/user_admin/house_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin page: House list</title>
</head>
<body>
    <a href="{% url "user_admin:house-create" %}">Create house</a>
    {% for house in houses %}
        <p><a href="{% url "user_admin:house-update" pk=house.pk %}">{{ house.address }}</a></p>
        <p>{{ house.company }}</p>
        <p>{{ house.material }}</p>
    {% endfor %}
</body>
</html>

templates/user_admin/resident_form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Create resident</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
</body>
</html>